# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-maven-enforcer-plugin-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build 'maven-examples-parent' with Maven
        run: mvn install --file maven-examples-parent/pom.xml
      - name: Build 'maven-enforcer-rule-api-example' with Maven
        run: mvn install --file maven-enforcer-rule-api-example/pom.xml
      - name: Build 'maven-enforcer-plugin-examples' with Maven
        run: mvn install --file maven-enforcer-plugin-examples/pom.xml

  build-maven-resources-plugin-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build 'maven-examples-parent' with Maven
        run: mvn install --file maven-examples-parent/pom.xml
      - name: Build 'maven-resources-plugin-examples' with Maven
        run: mvn install --file maven-resources-plugin-examples/pom.xml

  build-versions-maven-plugin-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build 'maven-examples-parent' with Maven
        run: mvn install --file maven-examples-parent/pom.xml
      - name: Build 'versions-maven-plugin-examples' with Maven
        run: mvn install --file versions-maven-plugin-examples/pom.xml

  build-owasp-dependency-check-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build 'maven-examples-parent' with Maven
      run: mvn install --file maven-examples-parent/pom.xml
    - name: Build 'owasp-dependency-check-examples' with Maven
      run: mvn install --file owasp-dependency-check-examples/pom.xml


